[Unit]
Wants=network-online.target mihomo-tproxy-watch.service
After=network-online.target

[Service]
ExecStartPost=/usr/lib/mihomo-tproxy/manage start
ExecStopPost=/usr/lib/mihomo-tproxy/manage stop
