mixed-port: 7890
ipv6: true
tproxy-port: 17894
routing-mark: 666
allow-lan: false
dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: 2001:2::/48
  nameserver: [https://1.1.1.1/dns-query]
proxies:
  - {name: dns, type: dns}
rules:
  - DST-PORT,53,dns
  - MATCH,DIRECT
